import { useState } from "react";
import { useMutation, useAction, useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Feather, Plus, X, Sparkles, Loader2, CheckCircle2, BookOpen } from "lucide-react";
import { toast } from "sonner";

export default function GenerateQuestion() {
  const createQuestion = useMutation(api.questions.create);
  const generateWithAI = useAction(api.ai.generateQuestion);
  const recentQuestions = useQuery(api.questions.list, { limit: 5 });
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [lastSavedId, setLastSavedId] = useState<string | null>(null);
  const [form, setForm] = useState({
    subject: "",
    topic: "",
    questionType: "",
    difficulty: "",
    bloomsLevel: "",
    gradeLevel: "",
    contentEnglish: "",
    correctAnswer: "",
    explanation: "",
    options: ["", "", "", ""],
    tags: [] as string[],
    tagInput: "",
    additionalContext: "",
  });

  const handleAIGenerate = async () => {
    if (!form.subject || !form.topic || !form.questionType || !form.difficulty || !form.bloomsLevel || !form.gradeLevel) {
      toast.error("Please fill in Subject, Topic, Type, Difficulty, Bloom's Level, and Grade Level first.");
      return;
    }
    setIsGenerating(true);
    try {
      const result = await generateWithAI({
        subject: form.subject,
        topic: form.topic,
        questionType: form.questionType,
        difficulty: form.difficulty,
        bloomsLevel: form.bloomsLevel,
        gradeLevel: form.gradeLevel,
        additionalContext: form.additionalContext || undefined,
      });
      if (result && result.contentEnglish) {
        setForm((f) => ({
          ...f,
          contentEnglish: result.contentEnglish ?? "",
          correctAnswer: result.correctAnswer ?? "",
          explanation: result.explanation ?? "",
          options: Array.isArray(result.options) && result.options.length === 4
            ? result.options
            : ["", "", "", ""],
        }));
        toast.success("Question generated by AI. Review and save.");
      } else {
        toast.error("AI generation returned an unexpected format. Please try again.");
      }
    } catch (err: any) {
      const msg = err?.message ?? "";
      toast.error("AI generation failed: " + (msg || "Please try again."));
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.subject || !form.topic || !form.questionType || !form.difficulty || !form.bloomsLevel || !form.gradeLevel || !form.contentEnglish) {
      toast.error("Please fill in all required fields");
      return;
    }
    setIsLoading(true);
    try {
      const options = form.questionType === "mcq" ? form.options.filter(Boolean) : undefined;
      const id = await createQuestion({
        subject: form.subject,
        topic: form.topic,
        questionType: form.questionType,
        difficulty: form.difficulty,
        bloomsLevel: form.bloomsLevel,
        gradeLevel: form.gradeLevel,
        contentEnglish: form.contentEnglish,
        correctAnswer: form.correctAnswer || undefined,
        explanation: form.explanation || undefined,
        options,
        tags: form.tags.length > 0 ? form.tags : undefined,
      });
      setLastSavedId(id);
      toast.success("Question inscribed in the archives.");
      setForm({
        subject: "", topic: "", questionType: "", difficulty: "", bloomsLevel: "",
        gradeLevel: "", contentEnglish: "", correctAnswer: "", explanation: "",
        options: ["", "", "", ""], tags: [], tagInput: "", additionalContext: "",
      });
    } catch {
      toast.error("The quill has faltered. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const addTag = () => {
    if (form.tagInput.trim() && !form.tags.includes(form.tagInput.trim())) {
      setForm((f) => ({ ...f, tags: [...f.tags, f.tagInput.trim()], tagInput: "" }));
    }
  };

  const difficultyColor: Record<string, string> = {
    easy: "text-green-700 bg-green-50 border-green-200",
    medium: "text-amber-700 bg-amber-50 border-amber-200",
    hard: "text-red-700 bg-red-50 border-red-200",
  };

  return (
    <div className="max-w-3xl" style={{ fontFamily: "'Libre Baskerville', serif" }}>
      {/* Scriptorium header */}
      <div className="mb-6 pb-4 border-b border-border">
        <div className="flex items-center gap-2 mb-1">
          <Feather className="w-5 h-5 text-primary" />
          <h3 className="text-lg font-bold" style={{ fontFamily: "'Lora', serif" }}>The Scriptorium</h3>
        </div>
        <p className="text-sm text-muted-foreground italic">
          Inscribe new questions into the archives. Use AI to generate or write manually.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Left: Metadata form */}
        <motion.div initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}>
          <div
            className="border-2 border-border p-5 relative bg-card"
            style={{ boxShadow: "2px 3px 8px rgba(74,63,53,0.08)" }}
          >
            <div className="text-xs text-muted-foreground uppercase tracking-widest mb-4 pb-2 border-b border-border" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>
              Metadata — Classification
            </div>
            <form id="question-form" onSubmit={handleSubmit} className="space-y-3">
              <div>
                <label className="text-sm italic text-muted-foreground mb-1 block">Subject *</label>
                <Select value={form.subject} onValueChange={(v) => setForm((f) => ({ ...f, subject: v }))}>
                  <SelectTrigger className="text-sm h-9"><SelectValue placeholder="Select subject" /></SelectTrigger>
                  <SelectContent>
                    {[["mathematics","Mathematics"],["physics","Physics"],["chemistry","Chemistry"],["biology","Biology"],["social_science","Social Science"],["humanities","Humanities"]].map(([v, l]) => (
                      <SelectItem key={v} value={v} className="text-sm">{l}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <label className="text-sm italic text-muted-foreground mb-1 block">Topic *</label>
                <Input value={form.topic} onChange={(e) => setForm((f) => ({ ...f, topic: e.target.value }))} placeholder="e.g. Quadratic Equations" className="text-sm h-9" />
              </div>
              <div>
                <label className="text-sm italic text-muted-foreground mb-1 block">Question Type *</label>
                <Select value={form.questionType} onValueChange={(v) => setForm((f) => ({ ...f, questionType: v }))}>
                  <SelectTrigger className="text-sm h-9"><SelectValue placeholder="Select type" /></SelectTrigger>
                  <SelectContent>
                    {[["mcq","MCQ"],["numerical","Numerical"],["short_answer","Short Answer"],["long_answer","Long Answer"],["case_study","Case Study"]].map(([v, l]) => (
                      <SelectItem key={v} value={v} className="text-sm">{l}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="text-sm italic text-muted-foreground mb-1 block">Difficulty *</label>
                  <Select value={form.difficulty} onValueChange={(v) => setForm((f) => ({ ...f, difficulty: v }))}>
                    <SelectTrigger className="text-sm h-9"><SelectValue placeholder="Level" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="easy" className="text-sm">Easy</SelectItem>
                      <SelectItem value="medium" className="text-sm">Medium</SelectItem>
                      <SelectItem value="hard" className="text-sm">Hard</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <label className="text-sm italic text-muted-foreground mb-1 block">Grade *</label>
                  <Select value={form.gradeLevel} onValueChange={(v) => setForm((f) => ({ ...f, gradeLevel: v }))}>
                    <SelectTrigger className="text-sm h-9"><SelectValue placeholder="Class" /></SelectTrigger>
                    <SelectContent>
                      {["6","7","8","9","10","11","12"].map((g) => (
                        <SelectItem key={g} value={`class_${g}`} className="text-sm">Class {g}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div>
                <label className="text-sm italic text-muted-foreground mb-1 block">Bloom's Level *</label>
                <Select value={form.bloomsLevel} onValueChange={(v) => setForm((f) => ({ ...f, bloomsLevel: v }))}>
                  <SelectTrigger className="text-sm h-9"><SelectValue placeholder="Taxonomy level" /></SelectTrigger>
                  <SelectContent>
                    {[["remember","Remember"],["understand","Understand"],["apply","Apply"],["analyze","Analyze"],["evaluate","Evaluate"],["create","Create"]].map(([v, l]) => (
                      <SelectItem key={v} value={v} className="text-sm">{l}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <label className="text-sm italic text-muted-foreground mb-1 block">Additional Context</label>
                <Input value={form.additionalContext} onChange={(e) => setForm((f) => ({ ...f, additionalContext: e.target.value }))} placeholder="e.g. Focus on Indian examples" className="text-sm h-9" />
              </div>
              <div>
                <label className="text-sm italic text-muted-foreground mb-1 block">Tags</label>
                <div className="flex gap-1">
                  <Input value={form.tagInput} onChange={(e) => setForm((f) => ({ ...f, tagInput: e.target.value }))} onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addTag())} placeholder="Add tag..." className="text-sm h-9 flex-1" />
                  <Button type="button" variant="outline" size="sm" onClick={addTag} className="h-9 px-2"><Plus className="w-3 h-3" /></Button>
                </div>
                {form.tags.length > 0 && (
                  <div className="flex flex-wrap gap-1 mt-2">
                    {form.tags.map((tag) => (
                      <span key={tag} className="text-xs bg-muted border border-border px-2 py-0.5 flex items-center gap-1 italic text-foreground">
                        #{tag}
                        <button type="button" onClick={() => setForm((f) => ({ ...f, tags: f.tags.filter((t) => t !== tag) }))}><X className="w-2.5 h-2.5" /></button>
                      </span>
                    ))}
                  </div>
                )}
              </div>
            </form>
            <span className="absolute bottom-3 right-3 text-primary/15 text-sm">✦</span>
          </div>
        </motion.div>

        {/* Right: Output / Question content */}
        <motion.div initial={{ opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }}>
          <div className="border-2 border-border p-5 h-full relative bg-card" style={{ boxShadow: "2px 3px 8px rgba(74,63,53,0.08)" }}>
            <div className="flex items-center justify-between mb-4 pb-2 border-b border-border">
              <div className="text-xs text-muted-foreground uppercase tracking-widest" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>
                Output — Question Content
              </div>
              <Button
                type="button"
                size="sm"
                variant="outline"
                onClick={handleAIGenerate}
                disabled={isGenerating}
                className="text-sm h-8 px-3 gap-1"
              >
                {isGenerating ? <Loader2 className="w-3 h-3 animate-spin" /> : <Sparkles className="w-3 h-3" />}
                {isGenerating ? "Generating..." : "AI Generate"}
              </Button>
            </div>
            <div className="space-y-3">
              <div>
                <label className="text-sm italic text-muted-foreground mb-1 block">Question Text (English) *</label>
                <Textarea
                  value={form.contentEnglish}
                  onChange={(e) => setForm((f) => ({ ...f, contentEnglish: e.target.value }))}
                  placeholder="Write the question or click AI Generate..."
                  className="text-sm min-h-[80px] resize-none text-foreground"
                  style={{ fontFamily: "'Lora', serif", fontStyle: "italic" }}
                />
              </div>

              {form.questionType === "mcq" && (
                <div>
                  <label className="text-sm italic text-muted-foreground mb-1 block">Options (A, B, C, D)</label>
                  <div className="space-y-1.5">
                    {form.options.map((opt, idx) => (
                      <div key={idx} className="flex items-center gap-2">
                        <span className="text-sm text-muted-foreground w-4" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>{String.fromCharCode(65 + idx)}.</span>
                        <Input
                          value={opt}
                          onChange={(e) => {
                            const newOpts = [...form.options];
                            newOpts[idx] = e.target.value;
                            setForm((f) => ({ ...f, options: newOpts }));
                          }}
                          placeholder={`Option ${String.fromCharCode(65 + idx)}`}
                          className="text-sm h-8 flex-1"
                        />
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div>
                <label className="text-sm italic text-muted-foreground mb-1 block">Correct Answer</label>
                <Input value={form.correctAnswer} onChange={(e) => setForm((f) => ({ ...f, correctAnswer: e.target.value }))} placeholder="The correct answer..." className="text-sm h-9" />
              </div>

              <div>
                <label className="text-sm italic text-muted-foreground mb-1 block">Explanation</label>
                <Textarea value={form.explanation} onChange={(e) => setForm((f) => ({ ...f, explanation: e.target.value }))} placeholder="Explain the solution..." className="text-sm min-h-[60px] resize-none" />
              </div>
            </div>
            <span className="absolute bottom-3 right-3 text-primary/15 text-sm">✦</span>
          </div>
        </motion.div>
      </div>

      {/* Submit */}
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="mt-6 flex items-center gap-4">
        <Button form="question-form" type="submit" disabled={isLoading} className="px-8">
          {isLoading ? (
            <span className="flex items-center gap-2"><Loader2 className="w-4 h-4 animate-spin" />Inscribing...</span>
          ) : (
            <span className="flex items-center gap-2"><Feather className="w-4 h-4" />Inscribe in Archives</span>
          )}
        </Button>
        <p className="text-sm text-muted-foreground italic">Questions are added to the bank for translation and evaluation.</p>
      </motion.div>

      {/* Recently Added Questions List */}
      {recentQuestions && recentQuestions.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mt-8"
        >
          <div className="flex items-center gap-2 mb-3 pb-2 border-b border-border">
            <BookOpen className="w-4 h-4 text-primary" />
            <span className="text-xs uppercase tracking-widest text-muted-foreground" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>
              Recently Added — Question Bank
            </span>
          </div>
          <div className="space-y-2">
            <AnimatePresence>
              {recentQuestions.map((q, i) => (
                <motion.div
                  key={q._id}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05 }}
                  className={`border border-border p-3 relative ${lastSavedId === q._id ? "border-primary/50 bg-primary/5" : "bg-card"}`}
                  style={{ boxShadow: "1px 2px 4px rgba(74,63,53,0.06)" }}
                >
                  {lastSavedId === q._id && (
                    <span className="absolute top-2 right-2 flex items-center gap-1 text-xs text-primary" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>
                      <CheckCircle2 className="w-3 h-3" /> just added
                    </span>
                  )}
                  <div className="flex items-start gap-2 pr-16">
                    <div className="flex-1 min-w-0">
                      <p className="text-xs leading-relaxed text-foreground line-clamp-2" style={{ fontFamily: "'Lora', serif", fontStyle: "italic" }}>
                        {q.contentEnglish}
                      </p>
                      <div className="flex flex-wrap items-center gap-1.5 mt-1.5">
                        <span className="text-xs text-muted-foreground capitalize" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>
                          {q.subject.replace("_", " ")}
                        </span>
                        <span className="text-muted-foreground/40 text-xs">·</span>
                        <span className="text-xs text-muted-foreground italic">{q.topic}</span>
                        <span className="text-muted-foreground/40 text-xs">·</span>
                        <span className={`text-xs px-1.5 py-0.5 border rounded-sm capitalize ${difficultyColor[q.difficulty] ?? "text-muted-foreground bg-muted border-border"}`}>
                          {q.difficulty}
                        </span>
                        <span className="text-xs text-muted-foreground uppercase" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>
                          {q.questionType.replace("_", " ")}
                        </span>
                      </div>
                    </div>
                  </div>
                  {q.correctAnswer && (
                    <div className="mt-2 pt-2 border-t border-border/50">
                      <span className="text-xs text-muted-foreground italic">Answer: </span>
                      <span className="text-xs text-foreground">{q.correctAnswer}</span>
                    </div>
                  )}
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        </motion.div>
      )}
    </div>
  );
}